# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist =
    py{310, 311, 312}-flask2,
    py{311, 312, 313, 314}-flask3
    pypy3.10-flask2
    pypy3.10-flask3
    pypy3.11-flask2
    pypy3.11-flask3
    doc

[testenv]
commands = {posargs:inv test qa}
deps =
    flask2: flask<3.0.0
    flask3: flask>=3.0.0
    -r{toxinidir}/requirements/test.pip
    -r{toxinidir}/requirements/develop.pip

[testenv:pypy3.10-flask{2,3}]
deps =
    {[testenv]deps}
    rpds-py<0.28
commands = {posargs:inv test}

[testenv:pypy3.11-flask{2,3}]
deps =
    {[testenv]deps}
    rpds-py<0.30
commands = {posargs:inv test}

[testenv:doc]
changedir = doc
deps = .[doc]
commands = sphinx-build -b html -d {envtmpdir}/doctrees . {envtmpdir}/html
